# conda environment file for the project. Install it with:
# conda env create -f environment.yml
name: medio
channels:
  - anaconda
  - conda-forge
dependencies:
  - python >= 3.6
  - numpy >= 1.18.1
  - itk == 5.0.1
  - nibabel >= 3.0.2
  - pydicom >= 2.0.0
